add typing to functions
fi-ksi/web-backend pull request #185
Opened 2022-10-18 18:50 UTC by jburget

2022-10-23 14:58 UTC, esoadamo requested changes
Moc díky za projití a doplnění! Jen miminální připomínky/dotazy

2022-10-23 14:58 UTC, esoadamo commented on util/task.py
> +def points_per_module(task_id: int, user_id: int) -> List[...]:
Tady je `...` (to je Any?) naschvál? Pokud to zabere *smysluplně hondě* energie, navrhuji co nejpřesnější typování. 
Alternativně si nejsem jistý, od kdy tuhle konstrukci s tečkami Python podporuje

2022-10-23 14:58 UTC, esoadamo commented on util/task.py
> +from typing import Any
Mohl bys prosím sjednotit všechno `from typing import ` do méně řádků?

2022-10-23 14:58 UTC, esoadamo commented on util/task.py
> +def after_deadline() -> set[int]:
... `from typing import Set`

```suggestion
def after_deadline() -> Set[int]:
```
Navrhuji se držet staršího způsobu typování, kvůli kompatibilitě s verzí Pythonu na backendu

2022-10-23 14:58 UTC, esoadamo commented on util/task.py
> +def after_deadline() -> set[int]:
A stejně tka prosím všechny výskyty `set`

2022-10-26 12:44 UTC, jburget commented on util/task.py
> +def points_per_module(task_id: int, user_id: int) -> List[...]:
Třeba návratová hodnota prerequisites v TypedDict je vytvořená rekurzivním převedením objektu prerequisite na nějakou hierarchii seznamů, takže to se dává typing dost špatně. A jinak to byly zase objekty z SQL dotazů, takže jsem to vesměs jen odstranil.

2022-10-26 14:10 UTC, esoadamo requested changes

2022-10-26 14:10 UTC, esoadamo commented on util/task.py
> +        -> Tuple[model.Task, float, model.Wave, model.Prerequisite]:
Nevypadlo tady `List`?
```suggestion
        -> List[Tuple[model.Task, float, model.Wave, model.Prerequisite]]:
```

2022-10-26 18:04 UTC, esoadamo approved these changes

2022-10-26 18:04 UTC, merged